package com.yto.template.module.bean;

/*
 * 所有存在同一个SharedPreference里的值都需要一个唯一的key，
 * 为了保证这些key的唯一性，我们借用就了enum的特性，
 * 用的时候将enum转成String使用即可
 */
public enum UniqueKey {

    APP_MOBILE, TOKEN, FULL_NAME, TELEPHONE, PHOTO_URL, APP_USER_NAME, PHOTO_SIZE, QR_CODE, PLATE,

    VEHICLE_NO, BIND, SCAN, TRANS_NUMBER, PRE_STATUS_TIME, FIRST_SIGN, FIRST_SEND, FIRST_EXCEPTION,

    MODE, MODE_ONE, MODE_TWO, RAIDUS_SMALL, RAIDUS_BIG, MSG_COUNT, FENCE_FLOW_LOCK, FENCE_STATUS_LOCK,

    GATHER_INTERVAL, PACK_INTERVAL, DRAFT_BOX, BeBindByOther, ACTION_LOG, UUID, SPEED_GATHER_INTERVAL,

    ABNORMAL_OFF_SPEED_GATHER_NUMBER, AVERAGE_SPEED, DRAFT_CHECK_CYCLE, MESSAGE_EXPIRED_TIME, OFFLINE_FENCE,

    LOC_LON, LOC_LAT, OFFLINE_FENCE_TAG, EXCEP_TRANS_NO, START_TIME, REPORT_TYPE, JPUSH_ALIAS, GOD_MODE,

    PLATE_RECORD, TICK_LEFT, TICK_QUIT_AT, FIRST_LOGIN, COMMENTS_URL, QQ_GROUP_NUM, QQ_GROUP_ANDROID_KEY,

    REPORT_SPEED_2000, REPORT_SPEED_2100, REPORT_SPEED_2800, WAYBILL_ITEMS, INPUT_TYPE, FIRST_USE_PERMISSION,

    FIRST_PRECETION_TIP, FIRST_UPGRADE


}
